# Q-Table Learning

In [7]:
import gym
import numpy as np

### Load the environment

In [8]:
env = gym.make('FrozenLake-v0')

[2017-08-04 14:37:51,275] Making new env: FrozenLake-v0


In [9]:
print(env)

<TimeLimit<FrozenLakeEnv<FrozenLake-v0>>>


### Implement Q-Table learning algorithm

In [3]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [5]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.4325


In [6]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  1.16083332e-01   2.75595154e-03   5.17220679e-03   2.52083377e-03]
 [  3.40364186e-04   5.93938554e-04   8.13614425e-05   2.08047401e-01]
 [  5.67424095e-04   5.98098599e-04   2.47198841e-03   3.02818481e-02]
 [  2.94269456e-04   3.56505742e-04   5.49496446e-04   1.02042617e-02]
 [  2.01289488e-01   7.62714762e-04   1.42945622e-04   5.26121210e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.59172067e-03   5.39911697e-06   5.05916033e-04   1.19295551e-07]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.33650612e-04   8.51876577e-04   7.75275105e-04   2.71365926e-01]
 [  0.00000000e+00   4.86585535e-02   2.76509190e-04   0.00000000e+00]
 [  5.10481532e-01   5.18520251e-04   7.02851214e-04   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   2.71492630e-01   0